### ISSUE TITLE
Error: Get /orders

### ISSUE THREAD

**Issue by JinhaJjing** [Yaneodoo/bistroad-order-service#1]
![image](https://user-images.githubusercontent.com/37143309/93625689-5842f480-fa1d-11ea-9c97-07eb6989f67e.png)

GET명령의 /orders를 실행했을 때 발생한 오류 메시지입니다.
원인이 무엇인가요?

**Comment by woodyn1002** [comment]
최근 변경했던 Review API의 URL가 Order 서비스에 적용되지 않았네요..
이슈 감사합니다!
